# Background and foreground colors
background = #090d15
foreground = #b4d0dd

# Standard colors
palette = 0=#090d15
palette = 1=#6e7b91
palette = 2=#667e8c
palette = 3=#7e96a5
palette = 4=#97a6bb
palette = 5=#6d7b91
palette = 6=#86a0ad
palette = 7=#b4d0dd

# Bright colors
palette = 8=#63666c
palette = 9=#919fbb
palette = 10=#88a2b5
palette = 11=#a1bbcf
palette = 12=#bbcce7
palette = 13=#909fbb
palette = 14=#a9c6d7
palette = 15=#a4e2ff
