background            #090d15
foreground            #b4d0dd

# black
color0  #090d15
color8  #63666c

# red
color1  #6e7b91
color9  #919fbb

# green
color2  #667e8c
color10 #88a2b5

# yellow
color3  #7e96a5
color11 #a1bbcf

# blue
color4  #97a6bb
color12 #bbcce7

# magenta
color5  #6d7b91
color13 #909fbb

#cyan
color6  #86a0ad
color14 #a9c6d7

#white
color7  #b4d0dd
color15 #a4e2ff


